<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.32
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
<div id="footer">
    <div class="container">

        &copy; <a href="http://board.streamerspanel.com/">board.streamerspanel.com</a>
        <small>   &raquo; <a href="http://changelog.streamerspanel.com/" target="_blank">Changelog</a></small>


        <br/>

        <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">StreamersPanel v 0.32</span> von
        <a xmlns:cc="http://creativecommons.org/ns#" href="http://board.streamerspanel.de" property="cc:attributionName"
           rel="cc:attributionURL">
            David Schomburg</a> ist lizenziert unter einer

        <a rel="license" href="http://login.streamerspanel.de/user/terms">
            Lizenz</a>.

    </div>
    <!-- /.container -->

</div> <!-- /#footer -->
</body>
</html>