<?php
/**
* Created by David Schomburg (DashTec - Services)
*      www.dashtec.de
*
*  S:P (StreamersPanel)
*  Support: http://board.streamerspanel.de
*
*  v 0.21
*
*  Kundennummer:   @KDNUM@
*  Lizenznummer:   @RECHNR@
* Lizenz: http://login.streamerspanel.de/user/terms
*/
?>
<!doctype html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <title><?= $site_title ?></title>
    <meta charset="iso-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <link href="/css/ajaxuploader.css" rel="stylesheet">

    <!-- Styles -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/css/bootstrap-overrides.css" rel="stylesheet">

    <link href="/css/ui-lightness/jquery-ui-1.8.21.custom.css" rel="stylesheet">
    <link href="/css/components/signin.css" rel="stylesheet" type="text/css">
    <link href="/css/slate.css" rel="stylesheet">
    <link href="/css/slate-responsive.css" rel="stylesheet">

    <link href="/css/pages/invoice.css" rel="stylesheet">

    <link href="/css/pages/reports.css" rel="stylesheet">
    <link href="/css/msgGrowl.css" rel="stylesheet">
    <link href="/js/plugins/msgAlert/css/msgAlert.css" rel="stylesheet">

    <!-- Javascript -->
    <script src="/js/jquery-1.7.2.min.js"></script>
    <script src="/js/jquery-ui-1.8.21.custom.min.js"></script>
    <script src="/js/jquery.ui.touch-punch.min.js"></script>
    <script src="/js/bootstrap.js"></script>

    <script src="/js/plugins/msgGrowl/js/msgGrowl.js"></script>
    <script src="/js/plugins/msgAlert/js/msgAlert.js"></script>
    <script src="/js/plugins/timepicker/jquery.ui.timepicker.min.js"></script>
    <script src="/js/plugins/colorpicker/js/bootstrap-colorpicker.js"></script>

    <script src="/js/Slate.js"></script>
    <script src="/js/ui-elements.js"></script>
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <script src="/js/ajaxuploader.min.js"></script>


    <script type="text/javascript">
        $(window).ready(function(){
            $(".smalluploader").SmallFileUploader({
                endpoint: "src/ajaxuploader.php",
                maxAllowedFiles: 3,
                maxFileSize: 1024 * 1024 * 1,
                allowedTypes: ["jpeg", "jpg", "png", "gif", "pdf"],
                onInit: function(uploader){
                    console.log("Uploader initialized");
                },
                onEnqueue: function(file){
                    console.log("File Enqueued");
                },
                onDequeue: function(file) {
                    console.log("File Dequeued");
                },
                onClearAll: function(uploader){
                    console.log("Queue Cleared");
                },
                onUploadStart: function(uploader){
                    console.log("Upload started");
                    return true;
                },
                onUploadFail: function(file){
                    console.log("File Failed");
                },
                onUploadComplete: function(file){
                    console.log("File Complete");
                },
                onAllComplete: function(uploader){
                    console.log("All Complete");
                }
            });

            prettyPrint();
        });
    </script>


</head>
<body>