<?php
/**
* Created by David Schomburg (DashTec - Services)
*      www.dashtec.de
*
*  S:P (StreamersPanel)
*  Support: http://board.streamerspanel.de
*
*  v 0.30
*
*  Kundennummer:   @KDNUM@
*  Lizenznummer:   @RECHNR@
*  Lizenz: http://login.streamerspanel.de/user/terms
*/
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= $site_title ?></title>
    <meta charset="iso-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">


    <!-- Styles -->

    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/css/bootstrap-overrides.css" rel="stylesheet">

    <link href="/css/ui-lightness/jquery-ui-1.8.21.custom.css" rel="stylesheet">
    <link href="/css/components/signin.css" rel="stylesheet" type="text/css">

    <link href="/css/pages/invoice.css" rel="stylesheet">
    <link href="/css/pages/reports.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/msgGrowl.css" type="text/css" media="screen" title="no title" charset="utf-8" />

    <link href="/js/plugins/timepicker/jquery.ui.timepicker.css" rel="stylesheet">
    <link href="/js/plugins/lightbox/themes/evolution-dark/jquery.lightbox.css" rel="stylesheet">
    <link href="/js/plugins/colorpicker/css/colorpicker.css" rel="stylesheet">


    <link href="/css/slate.css" rel="stylesheet">
    <link href="/css/slate-responsive.css" rel="stylesheet">
    <link href="/css/pages/ui-elements.css" rel="stylesheet">
    <!-- UPLOADER -->
    <link rel="stylesheet" href="/css/listTheme/style.css" type="text/css" media="all" />





    <!-- JS -->
    <script src="/js/jquery-1.7.2.min.js"></script>
    <script src="/js/jquery-ui-1.8.21.custom.min.js"></script>
    <script src="/js/jquery.ui.touch-punch.min.js"></script>
    <script src="/js/bootstrap.js"></script>

    <!-- Growl -->
    <script src="/js/plugins/msgAlert/js/msgAlert.js"></script>


    <!-- SET UP AXUPLOADER-->
    <script type="text/javascript" src="/js/ajaxupload-min.js"></script>
    <script type="text/javascript" charset="utf-8" src="/js/msgGrowl.js"></script>





</head>
<body>