<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.21
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 * Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
<div id="content">
    <div class="container">
        <div class="row">
            <div class="span9">

                <div class="widget">

                    <div class="widget-content">
                        <div class="widget widget-table">
                            <div class="widget-header">
                                <h3>
                                    <i class="icon-th-list"></i>
                                    Datein
                                </h3>
                            </div>
                            <!-- /widget-header -->
                            <div class="widget-content">
                                <form method="post" action="/sap/filemanager/playlist">
                                    <table class="table table-striped table-bordered table-highlight" id="example">
                                        <thead>
                                        <tr>
                                            <th>Playlist</th>
                                            <th>Titel in Playliste</th>
                                            <th>Spielzeit</th>
                                            <th>Aktion</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        $results = DB::query("SELECT * FROM playlist WHERE user_id=%s", $_SESSION['user_id']);
                                        foreach ($results as $row) {
                                            echo '<form action="/sap/filemanager/playlist" method="post"><tr>';
                                            echo "<td>" . $row['playlist_name'] . "</td> \n";
                                            DB::query("SELECT * FROM playlist_mp3_rel WHERE playlist_id=%s", $row['id']);
                                            $counter = DB::count();
                                            echo "<td>" . $counter . "</td> \n";
                                            echo "<td> </td> \n";
                                            echo '<td>
                                            <select name="pllstaction" onchange="this.form.submit()" >
                                            <option>bitte wählen</option>
                                            <option value="activ#' . $row['id'] . '">Bearbeiten</option>
                                            <option value="play#' . $row['id'] . '">Zufällig</option>
                                            <option value="play#' . $row['id'] . '"></option>
                                            <option value="del#' . $row['id'] . '">Löschen</option>
                                            </select>
                                            </td> ' . "\n";
                                            echo '</tr></form>';
                                        }
                                        ?>
                                        </tbody>
                                    </table>
                                </form>
                            </div>
                            <!-- /widget-content -->
                        </div>
                    </div>
                    <!-- /widget-content -->

                </div>
                <!-- /widget -->

            </div>
            <!-- /span12 -->

            <div class="span3">

                <div class="widget">

                    <div class="widget-content">

                        <h3>Playliste hinzufügen</h3>

                        <form method="post" action="/sap/filemanager/playlist">
                            <input type="text" name="playlist_name" value=""/>
                            <input type="submit" name="addplaylst" id="submit_id" value="Anlegen"/>
                        </form>

                    </div>
                    <!-- /widget-content -->

                </div>
                <!-- /widget -->

            </div>
            <!-- /span3 -->
        </div>
        <!-- /row -->


    </div>
    <!-- /.container -->

</div> <!-- /#content -->