<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.35
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>

<div id="content">
    <div class="container">
        <div class="row">
            <div class="span6">

                <div class="widget">

                    <div class="widget-content">
                        <div class="widget widget-table">
                            <div class="widget-header">
                                <h3>
                                    <i class="icon-th-list"></i>
                                    In deiner Playliste
                                    <?= _('Titel on Playlist'); ?>
                                </h3>
                            </div>
                            <!-- /widget-header -->
                            <div class="widget-content">
                                <form method="post" action="/filemanager/playlist">
                                    <table class="table table-striped table-bordered table-highlight" id="example">
                                        <thead>
                                        <tr>
                                            <th><?= _('Titel') ?></th>
                                            <th><?= _('Größe') ?></th>
                                            <th><?= _('Bitrate') ?></th>
                                            <th><?= _('Spielzeit') ?></th>
                                            <th><?= _('Löschen') ?></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        $TIMEFUNC = new core\time\time();

                                        $Size ='0';
                                        $TimeSecond = '0';
                                        $mp3titel = DB::query("SELECT * FROM playlist_mp3_rel WHERE playlist_id=%s", $_SESSION['playlistactiv']);
                                        foreach ($mp3titel as $title) {

                                            $mp3 = DB::query("SELECT * FROM mp3 WHERE id=%s", $title['mp3_id']);
                                            foreach ($mp3 as $mp3tit) {
                                                echo '<form action="/filemanager/playlist" method="post" ><tr>';
                                                echo "<td>".$mp3tit['org_file_titel']."</td> \n";
                                                $MB = $mp3tit['size'] / 1048576;
                                                echo "<td>".round($MB, 2)."MB</td> \n";
                                                echo "<td>".$mp3tit['bitrate']."</td> \n";
                                                echo "<td>".$TIMEFUNC->seconds2Time($mp3tit['playtime'])."</td> \n";
                                                echo '<td><button class="btn btn-warning" name="delTitleFormEditPlaylist" value="'.$title['id'].'">Löschen</button></td>';
                                                echo '</tr></form>';
                                                $Size += $mp3tit['size'];
                                                $TimeSecond += $TIMEFUNC->seconds2TimeDay($mp3tit['playtime']);
                                            }
                                        }
                                        echo '<tr>';
                                        echo "<td></td> \n";
                                        echo "<td>";
                                        $FileSize = new core\file\filesize();
                                        echo $FileSize->format_filesize($Size);
                                        echo "</td> \n";
                                        echo "<td> </td> \n";
                                        echo "<td>";
                                        echo $TIMEFUNC->seconds2Time($TimeSecond);
                                        echo "</td> \n";
                                        echo "<td>---</td> \n";
                                        echo '</tr>';
                                        ?>
                                        </tbody>
                                    </table>
                                </form>
                            </div>
                            <!-- /widget-content -->
                        </div>
                    </div>
                    <!-- /widget-content -->

                </div>
                <!-- /widget -->

            </div>
            <!-- /span12 -->



            <div class="span6">

                <div class="widget">

                    <div class="widget-content">
                        <div class="widget widget-table">
                            <div class="widget-header">
                                <h3>
                                    <i class="icon-th-list"></i>
                                    <?= _('Datein im Speicher'); ?>
                                </h3>
                            </div>
                            <!-- /widget-header -->
                            <div class="widget-content">
                                <form method="post" action="/filemanager/playlist">
                                    <table class="table table-striped table-bordered table-highlight" id="example">
                                        <thead>
                                        <tr>
                                            <th><?= _('Titel') ?></th>
                                            <th><?= _('Größe') ?></th>
                                            <th><?= _('Bitrate') ?></th>
                                            <th><?= _('Spielzeit') ?></th>
                                            <th><?= _('Auswählen') ?></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        $results = DB::query("SELECT * FROM mp3_usr_rel WHERE user_id=%s", $_SESSION['account_id']);

                                        foreach ($results as $row) {
                                            $mp3titel = DB::query("SELECT * FROM mp3 WHERE id=%s", $row['mp3_id']);
                                            foreach ($mp3titel as $title) {
                                                echo '<form action="/filemanager/playlist" method="post"><tr>';
                                                echo "<td>".$title['org_file_titel']."</td> \n";
                                                $MB = $title['size'] / 1048576;
                                                echo "<td>".round($MB, 2)."MB</td> \n";
                                                echo "<td>".$title['bitrate']."</td> \n";
                                                echo "<td>".$TIMEFUNC->seconds2Time($title['playtime'])."</td> \n";
                                                echo '<td><button class="btn btn-success" value="'. $title['id']  .'" name="addTitleToplst"><img src="/image/fuge/plus-circle.png"></button></td>';
                                                echo '</tr></form>';
                                            }
                                        }
                                        ?>
                                        </tbody>
                                </table>
                                </form>
                            </div>
                            <!-- /widget-content -->
                        </div>
                    </div>
                    <!-- /widget-content -->

                </div>
                <!-- /widget -->

            </div>
            <!-- /span12 -->

        </div>
        <!-- /row -->


    </div>
    <!-- /.container -->

</div> <!-- /#content -->



