<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.19
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 * Lizenz: http://login.streamerspanel.de/user/terms
 */
?>

<div id="content">
    <div class="container">
        <div class="row">
            <div class="span6">

                <div class="widget">

                    <div class="widget-content">
                        <div class="widget widget-table">
                            <div class="widget-header">
                                <h3>
                                    <i class="icon-th-list"></i>
                                    In deiner Playliste
                                </h3>
                            </div>
                            <!-- /widget-header -->
                            <div class="widget-content">
                                <form method="post" action="/sap/filemanager/playlist">
                                    <table class="table table-striped table-bordered table-highlight" id="example">
                                        <thead>
                                        <tr>
                                            <th>Titel</th>
                                            <th>Größe</th>
                                            <th>Bitrate</th>
                                            <th>Spielzeit</th>
                                            <th>Löschen</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        $TIMEFUNC = new core\time\time();

                                        $Size ='0';
                                        $TimeSecond = '0';
                                        $mp3titel = DB::query("SELECT * FROM playlist_mp3_rel WHERE playlist_id=%s", $_SESSION['playlistactiv']);
                                        foreach ($mp3titel as $title) {

                                            $mp3 = DB::query("SELECT * FROM mp3 WHERE id=%s", $title['mp3_id']);
                                            foreach ($mp3 as $mp3tit) {
                                                echo '<form action="/filemanager/playlist/edit" method="post"><tr>';
                                                echo "<td>".$mp3tit['org_file_titel']."</td> \n";
                                                echo "<td>".$mp3tit['size']."</td> \n";
                                                echo "<td>".$mp3tit['bitrate']."</td> \n";
                                                echo "<td>".$mp3tit['playtime']."</td> \n";
                                                ?>
                                                <input type="hidden" value="<?php echo $title['id']; ?>" name="delTitel[id]">
                                                <?php
                                                echo "<td><input type='submit' value='Del' name='ddd' /></td> \n";
                                                echo '</tr></form>';
                                                $Size += $mp3tit['size'];
                                                $TimeSecond += $TIMEFUNC->time2Seconds($mp3tit['playtime']);
                                            }
                                        }
                                        echo '<form action="/filemanager/playlist" method="post"><tr>';
                                        echo "<td><input type='submit' value='Speichern' name='savepllst' /></td> \n";
                                        echo "<td>";
                                         $FileSize = new core\file\filesize();
                                        echo $FileSize->format_filesize($Size);
                                        echo "</td> \n";
                                        echo "<td> </td> \n";
                                        echo "<td>";
                                        echo $TIMEFUNC->seconds2Time($TimeSecond);
                                        echo "</td> \n";
                                        echo "<td>---</td> \n";
                                        echo '</tr></form>';
                                        ?>
                                        </tbody>
                                    </table>
                                </form>
                            </div>
                            <!-- /widget-content -->
                        </div>
                    </div>
                    <!-- /widget-content -->

                </div>
                <!-- /widget -->

            </div>
            <!-- /span12 -->



            <div class="span6">

                <div class="widget">

                    <div class="widget-content">
                        <div class="widget widget-table">
                            <div class="widget-header">
                                <h3>
                                    <i class="icon-th-list"></i>
                                    Dateien zur Auswahl
                                </h3>
                            </div>
                            <!-- /widget-header -->
                            <div class="widget-content">
                                <form method="post" action="/sap/filemanager/playlist">
                                    <table class="table table-striped table-bordered table-highlight" id="example">
                                        <thead>
                                        <tr>
                                            <th>Titel</th>
                                            <th>Größe</th>
                                            <th>Bitrate</th>
                                            <th>Spielzeit</th>
                                            <th>Auswählen</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        $results = DB::query("SELECT * FROM mp3_usr_rel WHERE user_id=%s", $_SESSION['account_id']);

                                        foreach ($results as $row) {
                                            $mp3titel = DB::query("SELECT * FROM mp3 WHERE id=%s", $row['mp3_id']);
                                            foreach ($mp3titel as $title) {
                                                echo '<form action="/sap/filemanager/playlist" method="post"><tr>';
                                                echo "<td>".$title['org_file_titel']."</td> \n";
                                                echo "<td>".$title['size']."</td> \n";
                                                echo "<td>".$title['bitrate']."</td> \n";
                                                echo "<td>".$title['playtime']."</td> \n";
                                                ?>
                                                <input type="hidden" value="<?php echo $title['id']; ?>" name="addTitel[id]">
                                                <input type="hidden" value="<?php echo $title['org_file_titel']; ?>" name="addTitel[org_file_titel]; ?>]">
                                                <input type="hidden" value="my hidden value" name="addTitel[size]; ?>]">
                                                <?php
                                                echo "<td><input type='button' value='Add' name='addTitel' onclick='this.form.submit()'/></td> \n";
                                                echo '</tr></form>';
                                            }
                                        }
                                        ?>
                                        </tbody>
                                    </table>
                                </form>
                            </div>
                            <!-- /widget-content -->
                        </div>
                    </div>
                    <!-- /widget-content -->

                </div>
                <!-- /widget -->

            </div>
            <!-- /span12 -->

        </div>
        <!-- /row -->


    </div>
    <!-- /.container -->

</div> <!-- /#content -->



