<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.36
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>

<div id="content">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="widget widget-table">
                    <div class="widget-header">
                        <h3>
                            <i class="icon-th-list"></i>
                            <?= _('Datein') ?>
                        </h3>
                    </div>
                    <!-- /widget-header -->
                    <div class="widget-content">
                        <table class="table table-striped table-bordered table-highlight" id="example">
                            <thead>
                            <tr>
                                <th><?= _('Titel') ?></th>
                                <th><?= _('Größe') ?></th>
                                <th><?= _('Bitrate') ?></th>
                                <th><?= _('Spielzeit') ?></th>
                                <th><?= _('Löschen') ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php

                            $TIMEFUNC = new core\time\time();
                            $FILESIZE = new core\file\filesize();

                            $Size ='0';
                            $TimeSecond = '0';
                            $results = DB::query("SELECT * FROM mp3_usr_rel WHERE user_id=%s", $_SESSION['account_id']);
                            foreach ($results as $row) {
                                $mp3titel = DB::query("SELECT * FROM mp3 WHERE id=%s", $row['mp3_id']);
                                foreach ($mp3titel as $title) {
                                    echo '<form action="/filemanager/list" method="post"><tr>';
                                    echo "<td>".$title['org_file_titel']."</td> \n";
                                    $MB = $title['size'] / 1048576;
                                    echo "<td>".round($MB, 2)." MB</td> \n";
                                    echo "<td>".$title['bitrate']."</td> \n";
                                    echo "<td>".$TIMEFUNC->seconds2Time($title['playtime'])."</td> \n";
                                    echo '<td><button class="btn btn-danger" type="submit" value="'.$row['id'].'" name="DelFromDB" >Löschen</button></td>';
                                    echo '</tr></form>';

                                    $Size += $title['size'];
                                    $TimeSecond += $title['playtime'];




                                }
                            }

                            // TODO: Aus der DB und dem Ordner löschen!
                            ?>
                            <td>
                                    <?= _('Gesamtstatistiken') ?>
                            </td>
                            <td>
                                <?php
                                        $FileSize = new core\file\filesize();
                                             $Size =$Size / 1073741824 ;
                                        echo round($Size, 2) . "GB";
                                ?>
                            </td>
                            <td>
                                <?php


                                ?>
                            </td>
                            <td>
                                <?php
                                            echo $TIMEFUNC->seconds2TimeDay($TimeSecond);
                                ?>
                            </td>
                            <td>
                                <?php


                                ?>
                            </td>
                            </tbody>
                        </table>
                    </div>
                    <!-- /widget-content -->
                </div>
                <!-- /widget -->
            </div>
            <!-- /span12 -->
        </div>
        <!-- /row -->
    </div>
    <!-- /.container -->
</div> <!-- /#content -->
