<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.35
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
<div id="content">
    <div class="container">
        <div class="row">
            <div class="span9">

                <div class="widget">

                    <div class="widget-content">
                        <div class="widget widget-table">
                            <div class="widget-header">
                                <h3>
                                    <i class="icon-th-list"></i>
                                    <?= _('Dateien') ?>
                                </h3>
                            </div>
                            <!-- /widget-header -->
                            <div class="widget-content">
                                <form method="post" action="/filemanager/playlist">
                                    <table class="table table-striped table-bordered table-highlight" id="example">
                                        <thead>
                                        <tr>
                                            <th><?= _('Playlist') ?></th>
                                            <th><?= _('Titel in Playliste') ?></th>
                                            <th><?= _('Spielzeit') ?></th>
                                            <th><?= _('Aktion') ?></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        $results = DB::query("SELECT * FROM playlist WHERE user_id=%s", $_SESSION['account_id']);
                                        foreach ($results as $row) {
                                            echo '<form action="/filemanager/playlist" method="post"><tr>';
                                            echo "<td>" . $row['playlist_name'] . "</td> \n";
                                            DB::query("SELECT * FROM playlist_mp3_rel WHERE playlist_id=%s", $row['id']);
                                            $counter = DB::count();
                                            echo "<td>" . $counter . "</td> \n";
                                            echo "<td> </td> \n";
                                            echo '<td>'; ?>
                                            <button class="btn btn-warning" value="<?= $row['id'] ?>" name="editPlaylst" ><img src="/image/fuge/pencil.png" ></button>
                                            <button class="btn btn-info" value="<?= $row['id'] ?>" name="playListAction" ><img src="/image/fuge/arrow-circle.png" ></button>
                                            <button name="delPlaylst" value="<?= $row['id']?>" class="btn btn-danger" ><img src="/image/fuge/cross-circle.png"></button>
                                            </td>
                                            <?php
                                            echo '</tr></form>';
                                        }
                                        ?>
                                        </tbody>
                                    </table>
                                </form>
                            </div>
                            <!-- /widget-content -->
                        </div>
                    </div>
                    <!-- /widget-content -->

                </div>
                <!-- /widget -->

            </div>
            <!-- /span12 -->

            <div class="span3">

                <div class="widget">

                    <div class="widget-content">

                        <h3>Playliste hinzufügen<?= _('Dateien') ?></h3>

                        <form method="post" action="/filemanager/playlist">
                            <input type="text" name="playlist_name" value=""/>
                            <input type="submit" name="addplaylst" id="submit_id" value="<?= _('Anlegen') ?>"/>
                        </form>

                    </div>
                    <!-- /widget-content -->

                </div>
                <!-- /widget -->

            </div>
            <!-- /span3 -->
        </div>
        <!-- /row -->


    </div>
    <!-- /.container -->

</div> <!-- /#content -->