<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.21
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 * Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
<script type="text/javascript">
    $(window).ready(function(){
        $(".smalluploader").SmallFileUploader();
    });
</script>
<div id="content">
<div class="container">
<div class="row">
</div> <!-- /.row -->
<div class="row">
    <div class="span8">
        <div class="widget toolbar-bottom">
            <div class="widget-header">
                <h3>Upload Files</h3>
                <div class="widget-actions">
                </div> <!-- /.widget-actions -->
            </div> <!-- /.widget-header -->
            <div class="widget-content">

                <div id="wrapper">

                    <!-- uploader html begins here -->

                    <form action="/filemanager/upload" method="post" enctype="multipart/form-data">
                        <input type="file" id="file" name="files[]" multiple="multiple" accept="image/*" />
                        <input type="submit" value="Upload!" />

                </div>

            </div> <!-- /.widget-content -->
        </div> <!-- /.widget -->
    </div> <!-- /.span6 -->
</div> <!-- /.row -->
</div> <!-- /.container -->
</div> <!-- /#content -->


