<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.30
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
<div id="content">
    <div class="container">
        <div class="row">
        </div> <!-- /.row -->
        <div class="row">
            <div class="span12">
                <div class="widget toolbar-bottom">
                    <div class="widget-header">
                        <div class="widget-actions">
                        </div> <!-- /.widget-actions -->
                    </div> <!-- /.widget-header -->
                    <div class="widget-content">
                        <div id="wrapper">
                            <div id="uploader_div"></div>
                            <script type="text/javascript">
                                $('#uploader_div').ajaxupload({
                                    //remote upload path, can be set also in the php upload script
                                    remotePath : 'mp3collection/',
                                    //php/asp/jsp upload script
                                    url: '/filemanager/upload',
                                    //flash uploader url for not html5 browsers
                                    flash: 'uploader.swf',
                                    //other user data to send in GET to the php script
                                    data: '',
                                    //set asyncron upload or not
                                    async: true,
                                    //max number of files can be selected
                                    maxFiles: 9999,
                                    //array of allowed upload extesion, can be set also in php script
                                    allowExt:['mp3'],
                                    //function that triggers every time a file is uploaded
                                    success:function(fn){},
                                    //function that triggers when all files are uploaded
                                    finish:	function(file_names, file_obj){},
                                    //function that triggers if an error occuors during upload,
                                    error:	function(err, fn){},
                                    //start plugin enable or disabled
                                    enable:	true,
                                    //default 1Mb,if supported send file to server by chunks
                                    chunkSize:1048576,
                                    //max parallel connection on multiupload recomended 3, firefox
                                    //support 6, only for browsers that support file api
                                    maxConnections:3,
                                    //back color of drag & drop area, hex or rgb
                                    dropColor:'red',
                                    //set the id or element of area where to drop files. default self
                                    dropArea:'self',
                                    //if true upload will start immediately after drop of files
                                    //or select of files
                                    autoStart:false,
                                    //max thumbnial height if set generate thumbnial of images
                                    //on server side
                                    thumbHeight:0,
                                    //max thumbnial width if set generate thumbnial of images
                                    //on server side
                                    thumbWidth:0,
                                    //set the post fix of generated thumbs, default filename_thumb.ext
                                    thumbPostfix:'_thumb',
                                    //set the path here thumbs should be saved, if empty path
                                    //setted as remotePath
                                    thumbPath:'',
                                    //default same as image, set thumb output format, jpg, png, gif
                                    thumbFormat:'',
                                    //max file size of single file,
                                    maxFileSize:'250M',
                                    //integration with some form, set the form selector or object,
                                    //and upload will start on form submit
                                    form:null,
                                    //event that runs before submiting a form
                                    beforeSubmit:function(file_names, file_obj, formsubmitcall){
                                        formsubmitcall.call(this);
                                    },
                                    //if true allow edit file names before upload, by dblclick
                                    editFilename:true,
                                    //set if need to sort file list, need jquery-ui (not working)
                                    sortable:false,
                                    //this function runs before upload start for each file,
                                    //if return false the upload does not start
                                    beforeUpload:function(filename, file){return true;},
                                    //this function runs before upload all start, can be good
                                    //for validation
                                    beforeUploadAll:function(files){return true;},
                                    //function that trigger after a file select has been made,
                                    //paramter total files in the queue
                                    onSelect: function(files){},
                                    //function that trigger on uploader initialization. Usefull
                                    //if need to hide any button before uploader set up,
                                    //without using css
                                    onInit:	function(AU){},
                                    //set regional language, default is english,
                                    //avaiables: sq_AL, it_IT
                                    language:	'auto',
                                    //experimental feature, works on google chrome, for upload
                                    //an entire folder content
                                    uploadDir:false,
                                    //if true remove the file from the list after has been
                                    //uploaded successfully
                                    removeOnSuccess:false,
                                    //if true remove the file from the list if it has
                                    //errors during upload
                                    removeOnError:false,
                                    // tell if to show info upload speed, or where to
                                    //show the infos
                                    infoBox:false,
                                    //tell if to use bootstrap for theming buttons
                                    bootstrap:false
                                });
                            </script>
                        </div>
                    </div> <!-- /.widget-content -->
                </div> <!-- /.widget -->
            </div> <!-- /.span6 -->
        </div> <!-- /.row -->
    </div> <!-- /.container -->
</div> <!-- /#content -->


