<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.18
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 * Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
<div id="content">
<div class="container">
<div class="row">
</div> <!-- /.row -->
<div class="row">
    <div class="span8">
        <div class="widget toolbar-bottom">
            <div class="widget-header">
                <h3>Upload Files</h3>
                <div class="widget-actions">
                </div> <!-- /.widget-actions -->
            </div> <!-- /.widget-header -->
            <div class="widget-content">
                <script type="text/javascript">
                    $(window).ready(function(){
                        $(".smalluploader").SmallFileUploader({
				endpoint: '/sap/filemanager/post-upload?raw'
			});
                    });
                </script>

                <style type="text/css">
                    html { overflow-y: scroll; }
                    #wrapper { width: 600px; margin: 20px auto; overflow: hidden; }
                </style>

                <div class="smalluploader">
                    <div class="dragspace hidden">
                        <p class="zonemessage">Drag your files in here</p>
                        <p class="message">unlimited number of files allowed </p>
                    </div>
                    <div class="buttons">
                        <a class="addbutton greenbutton hidden">
                            Add File
                            <form action="/sap/filemanager/post-upload?raw" enctype="multipart/form-data" method="post" >
                                <input type="file" name="filedata"/>
                            </form>
                        </a>
                    </div>
                    <div class="uploadspace hidden"></div>
                    <div class="buttons">
                        <a class="startbutton redbutton hidden">Upload Files</a>
                        <a class="clearbutton redbutton hidden">Clear Queue</a>
                    </div>
                </div>
                </div>
            </div> <!-- /.widget-content -->
        </div> <!-- /.widget -->
    </div> <!-- /.span6 -->
</div> <!-- /.row -->
</div> <!-- /.container -->
</div> <!-- /#content -->


