<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.21
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 * Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
<div id="content">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="widget widget-table">
                    <div class="widget-header">
                        <h3>
                            <i class="icon-th-list"></i>
                            <?php echo _('View Stream'); ?>
                        </h3>
                    </div>
                    <!-- /widget-header -->
                    <div class="widget-content">
                        <table class="table table-striped table-bordered table-highlight" id="example">
                            <thead>
                            <tr>
                                <th><?php echo _('User'); ?></th>
                                <th><?php echo _('Stream name'); ?></th>
                                <th><?php echo _('Listener'); ?></th>
                                <th><?php echo _('Port'); ?></th>
                                <th><?php echo _('Server (Start/Stop)'); ?></th>
                                <th><?php echo _('Setup'); ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            $results = DB::query("SELECT * FROM sc_rel");
                            foreach ($results as $row) {
                                echo '<form action="/station/showstream" method="post"><tr>';
                                $sc_serv = DB::queryFirstRow("SELECT * FROM sc_serv_conf WHERE id=%s", $row['sc_serv_conf_id']);
                                $account = DB::queryFirstRow("SELECT * FROM accounts WHERE id=%s", $row['accounts_id']);
                                echo "<td>" . $account['vorname'] . " " . $account['nachname'] . "</td>";
                                echo "<td>" . $row['stream_userName'] . "</td> \n";
                                echo "<td>" . $sc_serv['MaxUser'] . "</td> \n";
                                echo '<td><a href="http://' . $_SERVER["HTTP_HOST"] . ':' . $sc_serv['PortBase'] . '">' . $sc_serv['PortBase'] . "</td> \n";
                                ?> </form>
                                <td>
                                    <form action="/station/showstream" method="post">
                                        <?php if ($row['sc_serv_pid'] == '0') {
                                            echo '<img src="/image/fuge/status-busy.png" >';
                                        } else {
                                            echo '<img src="/image/fuge/status.png">';
                                        } ?>
                                        <select name="onoffselc" size="1" onchange="this.form.submit()">
                                            <option <?php if (isset($row['sc_serv_pid'])) {
                                                echo 'selected';
                                            } ?> value="<?php echo $row['id'] . '.1' ?>">An
                                            </option>
                                            <option <?php if ($row['sc_serv_pid'] == '0') {
                                                echo 'selected';
                                            } ?> value="<?php echo $row['id'] . '.0' ?>">Aus
                                            </option>
                                        </select>
                                    </form>
                                </td>

                                <td>
                                    <form action="/station/showstream" method="post">
                                        <select name="changeConfServ" size="1" onchange="this.form.submit()">
                                            <option value=""></option>
                                            <option value="<?php echo $row['id'] . '.edit' ?>"><?php echo _('edit'); ?></option>
                                            <option value="<?php echo $row['id'] . '.clear' ?>"><?php echo _('delete'); ?></option>
                                        </select>
                                    </form>
                                </td>
                                <?php
                                echo '</tr>';
                            }
                            ?>
                            <form action="/station/showstream" method="post">
                                <tr>
                                    <td> <?php echo _('All Server'); ?></td>
                                    <td>

                                    </td>
                                    <td>

                                    </td>
                                    <td>

                                    </td>
                                    <td>
                                        <button type="submit" value="rebooton" name="switch"><?php echo _('restart Server'); ?></button>
                                        <button type="submit" value="on" name="switch"><?php echo _('all Server ON'); ?></button>
                                        <button type="submit" value="off" name="switch"><?php echo _('all Server OFF'); ?></button>
                                    </td>
                                    <td>

                                    </td>
                                </tr>
                            </form>
                            </tbody>
                        </table>
                    </div>
                    <!-- /widget-content -->
                </div>
                <!-- /widget -->
            </div>
            <!-- /span12 -->
        </div>
        <!-- /row -->
    </div>
    <!-- /.container -->
</div> <!-- /#content -->
<?php require __DIR__ . '/../footer.phtml' ?>

