<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.35
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
<div id="content">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="widget widget-table">
                    <div class="widget-header">
                        <h3>
                            <i class="icon-th-list"></i>
                            <?php echo _('Stream-Übersicht'); ?>
                        </h3>
                    </div>
                    <!-- /widget-header -->
                    <div class="widget-content">
                        <table class="table table-striped table-bordered table-highlight" id="example">
                            <thead>
                            <tr>
                                <th><?php echo _('Benutzer'); ?></th>
                                <th><?php echo _('Konfiguration'); ?></th>
                                <th><?php echo _('Server (Start/Stop)'); ?></th>
                                <th><?php echo _('Setup'); ?></th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php
                            $results = DB::query("SELECT * FROM sc_rel");
                            foreach ($results as $row) {
                                echo '<form action="/station/showstream" method="post"><tr>';
                                $sc_serv = DB::queryFirstRow("SELECT * FROM sc_serv_conf WHERE id=%s", $row['sc_serv_conf_id']);
                                $account = DB::queryFirstRow("SELECT * FROM accounts WHERE id=%s", $row['accounts_id']);
                                echo "<td>" . $account['vorname'] . " " . $account['nachname'] . "</td>";

                                echo "<td>";
                                            echo _('Stream-Bezeichnung: ') .'<b>'. $row['stream_userName'] .'</b>'."<br>";
                                            echo _('Max-Hörer: ') .'<b>'. $sc_serv['MaxUser'] .'</b>'. "<br>";
                                            if($row['sc_serv_pid'] != '0'){
                                                echo _('Port: ') .'<a href="http://' . $_SERVER["HTTP_HOST"] . ':' . $sc_serv['PortBase'] . '" target="_blank" >'.'<b>'. $sc_serv['PortBase'] .'</b>'. "</a><br>";
                                            }else{
                                                echo _('Port: ') .$sc_serv['PortBase']. "</a><br>";
                                            }

                                    $sc_serv_version = DB::queryFirstRow("SELECT * FROM sc_version WHERE id=%s", $row['sc_serv_version_id']);
                                    $sc_Trans_version = DB::queryFirstRow("SELECT * FROM sc_version WHERE id=%s", $row['sc_trans_version_id'] );
                                            echo _('Server-Version: ').'<b>'. $sc_serv_version['name'].'</b>'.'<br>';
                                            echo _('Transcoder: ').'<b>'. $sc_Trans_version['name'] .'</b>';
                                echo "</td>";

                                ?> </form>
                                <td>
                                    <form action="/station/showstream" method="post">
                                        <?php if ($row['sc_serv_pid'] == '0') {
                                            echo '<img src="/image/fuge/status-busy.png" >';
                                            ?>
                                            <button name="onoffselc" value="<?php echo $row['id'] . '.1' ?>" class="btn btn-success" value="<?php echo $row['id'] . '.0' ?>"><?= _('Starten') ?></button>
                                            <?php
                                        } else {
                                            echo '<img src="/image/fuge/status.png">';
                                            ?>
                                            <button name="onoffselc" value="<?php echo $row['id'] . '.0' ?>" class="btn btn-danger" value="<?php echo $row['id'] . '.0' ?>"><?= _('Stoppen') ?></button>
                                            <?php
                                        } ?>
                                    </form>
                                </td>
                                <td>
                                    <form action="/station/showstream" method="post">
                                    <button name="changeConfServ" value="<?php echo $row['id'] . '.edit' ?>" class="btn btn-secondary" ><img src="/image/fuge/pencil.png"></button>
                                    <button name="changeConfServ" value="<?php echo $row['id'] . '.clear' ?>" class="btn btn-danger" ><img src="/image/fuge/cross-circle.png" alt="Löschen"></button>
                                    </form>
                                </td>
                                <?php
                                echo '</tr>';
                            }
                            ?>
                            <form action="/station/showstream" method="post">
                                <tr>
                                    <td> <?php echo _('Alle Server'); ?></td>
                                    <td>

                                    </td>
                                    <td>
                                        <button type="submit" value="on" name="switch" class="btn btn-success"><?php echo _('Alle Server Ein'); ?></button>

                                        <button type="submit" value="rebooton" name="switch" class="btn btn-info"><?php echo _('Server Neustart'); ?></button>
                                        <button type="submit" value="off" name="switch" class="btn btn-danger"><?php echo _('Alle Server Aus'); ?></button>
                                    </td>
                                    <td>

                                    </td>
                                </tr>
                            </form>
                            </tbody>
                        </table>
                    </div>
                    <!-- /widget-content -->
                </div>
                <!-- /widget -->
            </div>
            <!-- /span12 -->
        </div>
        <!-- /row -->
    </div>
    <!-- /.container -->
</div> <!-- /#content -->
<?php require __DIR__ . '/../footer.phtml' ?>

