<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.36
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
<div id="content">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="widget widget-table">
                    <div class="widget-header">
                        <h3>
                            <i class="icon-th-list"></i>
                            <?php echo _('Streams'); ?>
                        </h3>
                    </div>
                    <!-- /widget-header -->
                    <div class="widget-content">
                        <table class="table table-striped table-bordered table-highlight" id="example">
                            <thead>
                            <tr>
                                <th><?php echo _('Streamname'); ?></th>
                                <th><?php echo _('Hörer'); ?></th>
                                <th><?php echo _('Port'); ?></th>
                                <th><?php echo _('Server (Start/Stop)'); ?></th>
                                <th><?php echo _('Einstellungen'); ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            $results = DB::query("SELECT * FROM sc_rel WHERE accounts_id=%s", $_SESSION['account_id']);
                            foreach ($results as $row) {
                                echo '<form action="/station/showstream" method="post"><tr>';
                                $sc_serv = DB::queryFirstRow("SELECT * FROM sc_serv_conf WHERE id=%s", $row['sc_serv_conf_id']);
                                $account = DB::queryFirstRow("SELECT * FROM accounts WHERE id=%s", $row['accounts_id']);
                                echo "<td>" . $row['stream_userName'] . "</td> \n";
                                echo "<td>" . $sc_serv['MaxUser'] . "</td> \n";
                                echo '<td><a href="http://' . $_SERVER["HTTP_HOST"] . ':' . $sc_serv['PortBase'] . '">' . $sc_serv['PortBase'] . "</td> \n";
                                ?> </form>
                                <td>
                                    <form action="/station/showstream" method="post">
                                        <?php if ($row['sc_serv_pid'] == '0') {
                                            echo '<img src="/image/fuge/status-busy.png" >';
                                     ?>
                                    <button name="onoffselc" value="<?php echo $row['id'] . '.1' ?>" class="btn btn-success">Starten</button>
                                     <?php
                                    } else {
                                            echo '<img src="/image/fuge/status.png">';
                                            ?>
                                            <button name="onoffselc" value="<?php echo $row['id'] . '.0' ?>" class="btn btn-danger">Stoppen</button>

                                        <?php
                                        } ?>
                                    </form>
                                </td>

                                <td>
                                    <form action="/station/showstream" method="post">
                                        <button class="btn btn-warning" name="changeConfServ" value="<?php echo $row['id'] . '.edit' ?>" ><img src="/image/fuge/pencil.png" ></button>
                                    </form>
                                </td>
                                <?php
                                echo '</tr>';
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                    <!-- /widget-content -->
                </div>
                <!-- /widget -->
            </div>
            <!-- /span12 -->
        </div>
        <!-- /row -->
    </div>
    <!-- /.container -->
</div> <!-- /#content -->
<?php require __DIR__ . '/../footer.phtml' ?>