<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.21
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 * Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
<div id="content">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="widget widget-table">
                    <div class="widget-header">
                        <h3>
                            <i class="icon-th-list"></i>
                            <?php echo _('Streams'); ?>
                        </h3>
                    </div>
                    <!-- /widget-header -->
                    <div class="widget-content">
                        <table class="table table-striped table-bordered table-highlight" id="example">
                            <thead>
                            <tr>
                                <th><?php echo _('Streamname'); ?></th>
                                <th><?php echo _('Listener'); ?></th>
                                <th><?php echo _('Port'); ?></th>
                                <th><?php echo _('Status'); ?></th>
                                <th><?php echo _('Playlist'); ?></th>
                                <th><?php echo _('DJ Start/Stop'); ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            $results = DB::query("SELECT * FROM sc_rel WHERE accounts_id=%s", $_SESSION['account_id']);
                            foreach ($results as $row) {
                                echo '<form action="/station/autodj" method="post"><tr>';
                                $account = DB::queryFirstRow("SELECT * FROM sc_serv_conf WHERE id=%s", $row['sc_serv_conf_id']);
                                echo '<td><a href="' . $_SERVER['HTTP_HOST'] . ':' . $account['PortBase'] . '">' . $row['stream_userName'] . '</a></td>';
                                echo "<td>" . $account['MaxUser'] . "</td> \n";
                                echo "<td>" . $account['PortBase'] . "</td> \n";
                                ?>
                                <td><?php if ($row['sc_serv_pid'] == '0') {
                                        echo '<img src="/image/fuge/status-busy.png" alt="Tanzmaus">';
                                    } else {
                                        echo '<img src="/image/fuge/status.png" alt="Tanzmaus">';
                                    } ?></td>

                                <td>
                                    <select name="playlstswitch" size="1" onchange="this.form.submit()">
                                        <option value=""></option>
                                        <?php
                                        $results = DB::query("SELECT * FROM playlist WHERE user_id=%s", $_SESSION['account_id']);
                                        foreach ($results as $pllst) {
                                            ?>
                                            <option <?php if ($pllst['id'] == $row['play_list_id']) {
                                                echo 'selected';
                                            } ?>
                                                value=" <?php echo $row['id'] . '.' . $pllst['id'] . '.' . $pllst['playlist_name']; ?>">
                                                <?php echo $pllst['playlist_name']; ?>
                                            </option>

                                        <?php
                                        }
                                        ?>
                                    </select>
                                </td>
                                <td><?php if ($row['sc_trans_pid'] == '0') {
                                        echo '<img src="/image/fuge/status-busy.png">';
                                    } else {
                                        echo '<img src="/image/fuge/status.png" >';
                                    } ?>

                                    <?php if ($row['sc_serv_pid'] == '0') {
                                        echo _('please start the stream server');
                                    } else {
                                        ?>

                                        <select name="djSwitch" size="1" onchange="this.form.submit()">
                                            <option <?php if (isset($row['sc_trans_pid'])) {
                                                echo 'selected';
                                            } ?> value="<?php echo $row['id'] . '.1' ?>"><?php echo _('ON'); ?>
                                            </option>
                                            <option <?php if ($row['sc_trans_pid'] == '0') {
                                                echo 'selected';
                                            } ?> value="<?php echo $row['id'] . '.0' ?>"><?php echo _('OFF'); ?>
                                            </option>
                                        </select>
                                    <?php
                                    } ?>
                                </td>
                                <?php
                                echo '</tr></form>';
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                    <!-- /widget-content -->
                </div>
                <!-- /widget -->
            </div>
            <!-- /span12 -->
        </div>
        <!-- /row -->
    </div>
    <!-- /.container -->
</div> <!-- /#content -->
<?php require __DIR__ . '/../footer.phtml' ?>