<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.36
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
<?php require_once __DIR__ . '/../header.phtml' ?>

<div id="header">

    <div class="container">

        <h1><a href="/"><?php echo _('Streamers:Panel'); ?></a></h1>

        <div id="info">

            <a href="javascript:;" id="info-trigger">
                <i class="icon-cog"></i>
            </a>

            <div id="info-menu">

                <div class="info-details">

                    <h4><?php echo _('Willkommen zurück, '); ?><?php echo $_SESSION['USERNAME']; ?></h4>

                    <p>
                        <a href="/logout"><?= _('Abmelden') ?></a>                    </p>
                    <br>
                </div>
                <!-- /.info-details -->

                <div class="info-avatar">

                    <img src='../../../../img/avatar.jpg' alt="avatar">

                </div>
                <!-- /.info-avatar -->

            </div>
            <!-- /#info-menu -->

        </div>
        <!-- /#info -->

    </div>
    <!-- /.container -->

</div> <!-- /#header -->


<div id="nav">

    <div class="container">

        <a href="javascript:;" class="btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <i class="icon-reorder"></i>
        </a>

        <div class="nav-collapse">

            <ul class="nav">

                <li class="nav-icon active">
                    <a href="/">
                        <i class="icon-home"></i>
                        <span><?php echo _('Home'); ?></span>
                    </a>
                </li>

                <li class="dropdown">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-th"></i>
                        <?php echo _('News'); ?>
                        <b class="caret"></b>
                    </a>

                    <ul class="dropdown-menu">
                        <li><a href="/news/messages"><?php echo _('News'); ?></a></li>

                    </ul>
                </li>

                <li class="dropdown">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-th"></i>
                        <?php echo _('Streams'); ?>
                        <b class="caret"></b>
                    </a>

                    <ul class="dropdown-menu">
                        <li><a href="/station/showstream"><?php echo _('Streams anzeigen'); ?></a></li>
                        <li><a href="/station/autodj"><?php echo _('AutoDj - Setup'); ?></a></li>
                        <!-- <li><a href="/sap/station/">Statistik</a></li> -->
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-camera"></i>
                        <?php echo _('Musikverwaltung'); ?>
                        <b class="caret"></b>
                    </a>

                    <ul class="dropdown-menu">
                        <li><a href="/filemanager/list"><?php echo _('MP3 '); ?>Übersicht</a></li>
                        <li><a href="/filemanager/playlist"><?php echo _('Playlist'); ?></a></li>
                        <li><a href="/filemanager/upload"><?php echo _('Upload'); ?></a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-camera"></i>
                        <?php echo _('DJ-Benutzer'); ?>
                        <b class="caret"></b>
                    </a>

                    <ul class="dropdown-menu">
                        <li><a href="/dj/list"><?php echo _('Benutzer anzeigen'); ?></a></li>
                        <li><a href="/dj/add"><?php echo _('DJ hinzufügen'); ?></a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-th"></i>
                        <?php echo _('Support'); ?>
                        <b class="caret"></b>
                    </a>

                    <ul class="dropdown-menu">
                        <!-- <li><a href="#">Radioserver-Konfiguration</a></li>     Templates für Streamconfigs-->
                        <li><a href="/support/list"><?php echo _('Tickets anzeigen'); ?></a></li>
                        <li><a href="/support/addticket"><?php echo _('Ticket eröffnen'); ?></a></li>

                    </ul>
                </li>
            </ul>

            <ul class="nav pull-right">

            </ul>

        </div>
        <!-- /.nav-collapse -->

    </div>
    <!-- /.container -->

</div> <!-- /#nav -->
