<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.19
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 * Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
    <div id="content">

        <div class="container">

            <div class="row">

                <div class="span8">

                    <div id="horizontal" class="widget widget-form">

                        <div class="widget-header">
                            <h3>
                                <i class="icon-pencil"></i>
                                <?php echo _('Add DJ'); ?>
                            </h3>
                        </div>
                        <!-- /widget-header -->

                        <div class="widget-content">

                            <form class="form-horizontal" method="post" action="/sap/dj/list">
                                <fieldset>
                                    <div class="control-group">
                                        <label class="control-label" for="input01"><?php echo _('DJ- Name'); ?></label>

                                        <div class="controls">
                                            <input type="text" class="input-large" name="dj_name" id="input01">
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="input01"><?php echo _('Name'); ?></label>

                                        <div class="controls">
                                            <input type="text" class="input-large" name="vorname" id="input01">
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="input01"><?php echo _('Surname'); ?></label>

                                        <div class="controls">
                                            <input type="text" class="input-large" name="nachname" id="input01">
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="input01"><?php echo _('Street'); ?></label>

                                        <div class="controls">
                                            <input type="text" class="input-large" name="street" id="input01">
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="input01"><?php echo _('Number'); ?></label>

                                        <div class="controls">
                                            <input type="text" class="input-large" name="hausnummer" id="input01">
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="input01"><?php echo _('Town'); ?></label>

                                        <div class="controls">
                                            <input type="text" class="input-large" name="ort" id="input01">
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="input01"><?php echo _('PLZ'); ?></label>

                                        <div class="controls">
                                            <input type="text" class="input-large" name="plz" id="input01">
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="input01"><?php echo _('Phone'); ?></label>

                                        <div class="controls">
                                            <input type="text" class="input-large" name="telefon" id="input01">
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="input01"><?php echo _('Mobile Phone'); ?></label>

                                        <div class="controls">
                                            <input type="text" class="input-large" name="handy" id="input01">
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="input01"><?php echo _('Mail'); ?></label>

                                        <div class="controls">
                                            <input type="text" class="input-large" name="mail" id="input01">
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="input01"><?php echo _('Skype'); ?></label>

                                        <div class="controls">
                                            <input type="text" class="input-large" name="skype" id="input01">
                                        </div>
                                    </div>

                                    <div class="form-actions">
                                        <button type="submit" class="btn btn-primary btn-large" name="entryDjUser">
                                            <?php echo _('Save'); ?>
                                        </button>
                                    </div>
                                </fieldset>
                            </form>

                        </div>
                        <!-- /widget-content -->

                    </div>


                </div>
                <!-- /span8 -->


                <div class="span4">

                    <div id="formToc" class="widget highlight">

                        <div class="widget-header">
                            <h3><b><?php echo _('Hints '); ?></b><?php echo _('DJ to add'); ?></h3>
                        </div>
                        <!-- /widget-header -->

                        <div class="widget-content">
                            <p><?php echo _('DJ user Identification'); ?></p>
                        </div>
                        <!-- /widget-content -->
                    </div>
                    <!-- /widget -->
                </div>
                <!-- /.span4 -->
            </div>
            <!-- /row -->
        </div>
        <!-- /.container -->
    </div> <!-- /#content -->

<?php require __DIR__ . '/../footer.phtml' ?>