<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.30
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
    <div id="content">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <div class="widget widget-table">
                        <div class="widget-header">
                            <h3>
                                <i class="icon-th-list"></i>
                                <?php echo _('DJ-User'); ?>
                            </h3>
                        </div>
                        <!-- /widget-header -->
                        <div class="widget-content">
                            <table class="table table-striped table-bordered table-highlight" id="example">
                                <thead>
                                <tr>
                                    <th><?php echo _('DJ - Name / (Loginname)'); ?></th>
                                    <th><?php echo _('Benutzerinformation'); ?></th>
                                    <th><?php echo _('Addresse'); ?></th>
                                    <th><?php echo _('Telefon'); ?></th>
                                    <th><?php echo _('Kontakt'); ?></th>
                                    <th><?php echo _('DJ vom Stream'); ?></th>
                                    <th><?php echo _('DJ-Aktiv?'); ?></th>
                                    <th><?php echo _('Einstellungen'); ?></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                $results = DB::query("SELECT * FROM dj_accounts WHERE dj_of_user_id=%s ", $_SESSION['account_id']);
                                foreach ($results as $row) {


                                    $dj_data = DB::queryFirstRow("SELECT * FROM accounts WHERE id=%s AND usr_grp='dj' ", $row['dj_accounts_id']);

                                        echo "<td>" . $row['dj_name'] .'<br>('. $dj_data['kundennummer'].")</td>";
                                        echo "<td>" . $dj_data['vorname'] . " " . $dj_data['nachname'] . "</td>";
                                        echo "<td>" . $dj_data['street'] .' '.$dj_data['hausnummer'].'<br>'.$dj_data['plz'].' '.$dj_data['ort']."</td> \n";
                                        echo "<td>"._('Phone')." <b>" . $dj_data['telefon'] . "</b><br>"._('Mobile').": <b> " . $dj_data['handy'] . "</b></td>";
                                        echo "<td>"._('Phone').": <b>".$dj_data['mail']."</b><br> "._('Phone')." <b>".$dj_data['skype']."</td> \n";
                                        $StreamName = DB::queryFirstRow("SELECT stream_userName FROM sc_rel WHERE id=%s", $row['dj_of_sc_rel_id']);
                                        echo '<td>'.$StreamName['stream_userName'].'</td>';
                                        ?><form action="/dj/list" method="post">
                                        <td>
                                            <?php if ($dj_data['is_aktiv'] == '1' ) {?>
                                                <button class="btn btn-danger" value="<?php echo 'is_aktiv.'.$row['dj_accounts_id'].'.0' ?>" name="editDjList" ><?= _('Sperren') ?></button>
                                            <?php
                                            }
                                            if ($dj_data['is_aktiv'] == '0') {
                                                ?>
                                                <button class="btn btn-success" value="<?php echo 'is_aktiv.'.$row['dj_accounts_id'].'.1' ?>" name="editDjList" ><?= _('Freischalten') ?></button>
                                            <?php
                                            }

                                            ?>
                                        </td>
                                        <td>

                                                <button class="btn btn-success" value="<?php echo 'djtoStation.'.$row['id'] ?>" name="editDjList" ><img src="/image/fuge/plus-circle.png"></button>
                                                <button class="btn btn-warning" value="<?php echo 'editDj.'.$row['id'] ?>" name="editDjList" ><img src="/image/fuge/pencil.png"></button>
                                                <button class="btn btn-warning" value="<?php echo 'newPass.'.$row['dj_accounts_id'] ?>" name="editDjList" ><img src="/image/fuge/key.png"></button>
                                                <button class="btn btn-danger" value="<?php echo 'delDj.'.$row['dj_accounts_id'] ?>" name="editDjList" ><img src="/image/fuge/cross-circle.png"></button>

                                        </td> </form>
                                        <?php
                                        echo '</tr>';




                                }
                                ?>
                                </tbody>
                            </table>
                        </div>
                        <!-- /widget-content -->
                    </div>
                    <!-- /widget -->
                </div>
                <!-- /span12 -->
            </div>
            <!-- /row -->
        </div>
        <!-- /.container -->
    </div> <!-- /#content -->
<?php require __DIR__ . '/../footer.phtml' ?>