<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.25
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
    <div id="content">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <div class="widget widget-table">
                        <div class="widget-header">
                            <h3>
                                <i class="icon-th-list"></i>
                                <?php echo _('DJ-User'); ?>
                            </h3>
                        </div>
                        <!-- /widget-header -->
                        <div class="widget-content">
                            <table class="table table-striped table-bordered table-highlight" id="example">
                                <thead>
                                <tr>
                                    <th><?php echo _('DJ - Name'); ?></th>
                                    <th><?php echo _('Benutzerinformation'); ?></th>
                                    <th><?php echo _('Addresse'); ?></th>
                                    <th><?php echo _('Telefon'); ?></th>
                                    <th><?php echo _('Kontakt'); ?></th>
                                    <th><?php echo _('DJ vom Stream'); ?></th>
                                    <th><?php echo _('Einstellungen'); ?></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                $results = DB::query("SELECT * FROM dj_accounts WHERE dj_of_user_id=%s", $_SESSION['account_id']);
                                foreach ($results as $row) {
                                    echo "<td>" . $row['dj_name'] . "</td>";
                                    echo "<td>" . $row['vorname'] . " " . $row['nachname'] . "</td>";
                                    echo "<td>" . $row['street'] .' '.$row['hausnummer'].'<br>'.$row['plz'].' '.$row['ort']."</td> \n";
                                    echo "<td>"._('Phone')." <b>" . $row['telefon'] . "</b><br>"._('Mobile').": <b> " . $row['handy'] . "</b></td>";
                                    echo "<td>"._('Phone').": <b>".$row['mail']."</b><br> "._('Phone')." <b>".$row['skype']."</td> \n";
                                    $StreamName = DB::queryFirstRow("SELECT stream_userName FROM sc_rel WHERE id=%s", $row['dj_of_sc_rel_id']);
                                    echo '<td>'.$StreamName['stream_userName'].'</td>';
                                    ?>
                                    <td>
                                        <form action="/dj/list" method="post">
                                            <select name="editDjList" size="1" onchange="this.form.submit()">
                                                <option value=""></option>
                                                <option value="<?php echo 'djtoStation.'.$row['id'] ?>"><?php echo _('Stream zum Benutzer hinzufügen'); ?></option>
                                               <!-- SOON  <option value="<?php echo 'editDj.'.$row['id'] ?>"><?php echo _('Benutzer bearbeiten'); ?></option> -->
                                                <option value="<?php echo 'delDj.'.$row['id'] ?>"><?php echo _('Benutzer löschen'); ?></option>
                                            </select>
                                        </form>
                                    </td>
                                    <?php
                                    echo '</tr>';
                                }
                                ?>
                                </tbody>
                            </table>
                        </div>
                        <!-- /widget-content -->
                    </div>
                    <!-- /widget -->
                </div>
                <!-- /span12 -->
            </div>
            <!-- /row -->
        </div>
        <!-- /.container -->
    </div> <!-- /#content -->
<?php require __DIR__ . '/../footer.phtml' ?>