<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.36
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
<div id="content">

    <div class="container">

        <div class="row">
            <div class="span12">

                <div id="big-stats-container" class="widget">

                    <div class="widget-content">


                        <div id="big_stats" class="cf">
                            <div class="stat">
                                <h4><?php echo _('Benutzer'); ?></h4>
                    <span class="value">
                        <?php
                        DB::query("SELECT * FROM accounts");
                        echo DB::count();
                        ?></span>
                            </div>
                            <!-- .stat -->

                            <div class="stat">
                                <h4><?php echo _('MP3'); ?></h4>
                    <span class="value">
                        <?php
                        DB::query("SELECT * FROM mp3");
                        echo DB::count();
                        ?></span>
                            </div>
                            <!-- .stat -->

                            <div class="stat">
                                <h4><?php echo _('Stream-Server'); ?></h4>
                    <span class="value">
                        <?php
                        DB::query("SELECT * FROM sc_serv_conf");
                        echo DB::count();
                        ?></span>
                            </div>
                            <!-- .stat -->

                            <div class="stat">
                                <h4><?php echo _('Neue Support Tickets'); ?></h4>
                    <span class="value">
                        <?php
                        DB::query("SELECT * FROM support WHERE status='offen'");
                        echo DB::count();
                        ?></span>
                            </div>
                            <!-- .stat -->
                        </div>

                    </div>
                    <!-- /widget-content -->

                </div>
                <!-- /widget -->

            </div>
            <!-- /span12 -->


            </div>
            <!-- /.row -->


        </div>
        <!-- /.container -->

    </div> <!-- /#content -->
<?php require __DIR__ . '/../footer.phtml' ?>