<?php
/**
 * Created by PhpStorm.
 * User: David
 * Date: 17.03.14
 * Time: 20:06
 */


?>
<script>
    $(function() {                       // On DOM ready
        $('#myModal').modal('show');     // Show the modal
    });
</script>

<div class="modal fade" id="myModal">
    <form action="/sap/support/view" method="post">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h3><?php echo _('Reply for Ticket'); ?></h3>
        </div>
        <div class="modal-body">
            <form action="/sap/support/view" method="post">
                <p><?php echo _('Reply:'); ?><br>
                    <textarea name="reptext" cols="500" rows="10"
                              style="width: 530px; height: 180px;" ></textarea>
                </p>
        </div>
        <div class="modal-footer">
            <input type="submit" name="entryAnswer" class="btn btn-primary" value="<?php echo _('Send'); ?>" />
        </div>
    </form>
</div>