<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.35
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
    <div id="content">

        <div class="container">

            <div class="row">

                <div class="span12">

                    <div class="widget widget-table">

                        <div class="widget-content">

                            <table class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th><?= _('Datum') ?></th>
                                    <th><?= _('Nachricht') ?></th>
                                    <th><?= _('Einstellungen') ?></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                foreach ($supportTickets as $row) {
                                    ?>
                                    <form action="/support/list" method="post">
                                        <tr>
                                            <td><?= $row['add_time'] ?></td>
                                            <td><?=
                                                $row['text'];
                                                $reptext = DB::query("SELECT * FROM support WHERE replyid=%s", $row['id']);
                                                foreach ($reptext as $repshow) {
                                                    if ($repshow['is_adm_answ'] == '') {
                                                        echo '<p><b>' . _('Admin:') . '<br></b>';
                                                    } else {
                                                        echo '<p><b>' . _('Antwort:') . '<br></b>';
                                                    }
                                                    echo $repshow['text'];
                                                    echo '</p>';
                                                }?>
                                            </td>
                                            <td>
                                                <button class="btn btn-info" name="sendreply"
                                                        value="edit.<?= $row['id'] ?>"><?= _('Anwtort senden') ?></button>
                                                <button class="btn btn-danger" name="delentry"
                                                        value="del.<?= $row['id'] ?>"><?= _('Löschen') ?></button>
                                            </td>
                                        </tr>
                                    </form>
                                <?php } ?>
                                </tbody>
                            </table>
                        </div>
                        <!-- /item-row -->

                    </div>
                    <!-- /widget-content -->

                </div>
                <!-- /widget -->

            </div>
            <!-- /span6 -->

        </div>
        <!-- /row -->

    </div>
    <!-- /.container -->

<?php require __DIR__ . '/../footer.phtml' ?>