<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.37
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
    <div id="content">

    <div class="container">

        <div class="row">

            <div class="span8">

                <div id="horizontal" class="widget widget-form">

                    <div class="widget-header">
                        <h3>
                            <i class="icon-pencil"></i>
                            <?php echo _('Benutzer-News'); ?>
                        </h3>
                    </div>
                    <!-- /widget-header -->

                    <div class="widget-content">

                        <form class="form-horizontal" action="/news/addnews" method="post">
                            <fieldset>
                                <div class="control-group">
                                    <label class="control-label" for="input01"><?php echo _('Überschrift'); ?></label>

                                    <div class="controls">
                                        <input type="text" class="input-large" name="headline" id="input01">

                                        <p class="help-block"><?php echo _('Überschrift für die Nachricht'); ?></p>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="textarea"><?php echo _('Nachricht'); ?></label>

                                    <div class="controls">
                                        <textarea class="input-large" id="textarea" name="message" rows="3"></textarea>
                                    </div>
                                </div>


                                <div class="control-group">
                                    <label class="control-label"><?php echo _('Nachricht auf der Login-Seite anzeigen'); ?></label>

                                    <div class="controls">
                                        <label class="radio">
                                            <input type="radio" id="optionsRadios1" name="login_news" value="1"
                                                   checked="">
                                            <?php echo _('Ja'); ?>
                                        </label>
                                        <label class="radio">
                                            <input type="radio" id="optionsRadios1" name="login_news" value="0">
                                            <?php echo _('Nein'); ?>
                                        </label>
                                    </div>
                                </div>


                                <div class="control-group">
                                    <label class="control-label"><?php echo _('Nachricht aktiv?'); ?></label>

                                    <div class="controls">
                                        <label class="radio">
                                            <input type="radio" id="optionsRadios4" name="is_aktiv" value="1"
                                                   checked="">
                                            <?php echo _('Nachricht anzeigen'); ?>
                                        </label>
                                        <label class="radio">
                                            <input type="radio" id="optionsRadios4" name="is_aktiv" value="0">
                                            <?php echo _('Nachricht verstecken'); ?>
                                        </label>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="select01">Typ der Anzeige</label>

                                    <div class="controls">
                                        <select id="select01">
                                            <option><?php echo _('Information (Grün)'); ?></option>
                                            <option><?php echo _('Warnung (Gelb)'); ?></option>
                                            <option><?php echo _('Fehler (Rot)'); ?></option>
                                        </select>
                                    </div>
                                    <?php echo _('comming soon'); ?>
                                </div>
                                <div class="form-actions">
                                    <button type="submit" name="eintragen" class="btn btn-primary btn-large">
                                        <?php echo _('Speichere Nachricht'); ?>
                                    </button>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                    <!-- /widget-content -->
                </div>

            </div>
            <!-- /span8 -->

            <div class="span4">

                <div id="formToc" class="widget highlight">

                    <div class="widget-header">
                        <h3><?php echo _('Nachricht beim Login anzeigen'); ?></h3>
                    </div>
                    <!-- /widget-header -->

                    <div class="widget-content">
                        <p>
                            <?php echo _('Beschreibung'); ?>
                        </p>

                    </div>
                    <!-- /widget-content -->

                </div>
                <!-- /widget -->

            </div>
            <!-- /.span4 -->

        </div>
        <!-- /row -->

    </div>
    <!-- /.container -->

</div> <!-- /#content -->
<?php require __DIR__ . '/../footer.phtml' ?>