<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.33
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
    <div id="content">

    <div class="container">

        <div class="row">

            <div class="span12">


                <div class="widget">

                    <div class="widget-header">
                        <h3><?php echo _('News'); ?></h3>
                    </div> <!-- /widget-header -->

                    <div class="widget-content">
                        <?php
                        foreach ($news_to_read as $row => $value) {

                            $account = DB::queryFirstRow("SELECT * FROM news WHERE id=%s", $value);
                                ?>
                                <div class="alert alert-<?php echo $account['type']; ?>">
                                    <form class="form-horizontal" action="/news/spwelcome" method="post">
                                        <button class="btn btn-info" name="close" value="<?php echo $account['id'] ?>"><?= _('X') ?></button>
                                    </form>
                                    <h4 class="alert-heading"><?php echo $account['headline']; ?></h4>
                                    <?php echo $account['message']; ?>
                                </div> <!-- ./alert -->
                            <?php
                        }
                        ?>
                    </div> <!-- /widget-content -->

                </div> <!-- /widget -->

            </div> <!-- /span6 -->

        </div> <!-- /span6 -->

    </div> <!-- /row -->

</div> <!-- /.container -->

</div> <!-- /#content -->
<?php require __DIR__ . '/../footer.phtml' ?>