<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.25
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
    <div id="content">

    <div class="container">

        <div class="row">

            <div class="span12">


                <div class="widget">

                    <div class="widget-header">
                        <h3><?php echo _('News'); ?></h3>
                    </div> <!-- /widget-header -->

                    <div class="widget-content">

                        <?php
                        $results = DB::query("SELECT * FROM news WHERE is_aktiv='1'");
                        foreach ($results as $row) {


                            $account = DB::queryFirstRow("SELECT * FROM news_to_read WHERE user_id=%s AND news_id=%s AND user_read_it=%s", $_SESSION['account_id'], $row['id'], 1 );
                            if ($account['id'] == false){
                                ?>
                                <div class="alert alert-<?php echo $row['type']; ?>">
                                    <form class="form-horizontal" action="/news/messages" method="post">
                                        <button class="close" name="close" value="<?php echo $row['id'] ?>"><?_('schließen') ?></button>
                                    </form>
                                    <h4 class="alert-heading"><?php echo $row['headline']; ?></h4>
                                    <?php echo $row['message']; ?>
                                </div> <!-- ./alert -->
                            <?php
                                 }




                        }
                        ?>
                    </div> <!-- /widget-content -->

                </div> <!-- /widget -->

            </div> <!-- /span6 -->

        </div> <!-- /span6 -->

    </div> <!-- /row -->

</div> <!-- /.container -->

</div> <!-- /#content -->
<?php require __DIR__ . '/../footer.phtml' ?>