<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.19
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 * Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
    <div id="content">

    <div class="container">

        <div class="row">

            <div class="span12">


                <div class="widget">

                    <div class="widget-header">
                        <h3><?php echo _('News'); ?></h3>
                    </div> <!-- /widget-header -->

                    <div class="widget-content">

                        <?php
                        $results = DB::query("SELECT * FROM news WHERE is_aktiv='1'");
                        foreach ($results as $row) {
                            ?>
                            <div class="alert alert-<?php echo $row['type']; ?>">
                                <a class="close" data-dismiss="alert" href="#">&times;</a>
                                <h4 class="alert-heading"><?php echo $row['headline']; ?></h4>
                                <?php echo $row['message']; ?>
                            </div> <!-- ./alert -->
                        <?php
                        }
                        ?>
                    </div> <!-- /widget-content -->

                </div> <!-- /widget -->

            </div> <!-- /span6 -->

        </div> <!-- /span6 -->

    </div> <!-- /row -->

</div> <!-- /.container -->

</div> <!-- /#content -->
<?php require __DIR__ . '/../footer.phtml' ?>