<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.18
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 * Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
    <div id="content">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="widget widget-table">
                    <div class="widget-header">
                        <h3>
                            <i class="icon-th-list"></i>
                            <?php echo _('User messages'); ?>
                        </h3>
                    </div>
                    <!-- /widget-header -->
                    <div class="widget-content">
                        <table class="table table-striped table-bordered table-highlight" id="example">
                            <thead>
                            <tr>
                                <th><?php echo _('Title'); ?></th>
                                <th><?php echo _('Message'); ?></th>
                                <th><?php echo _('Login-News?'); ?></th>
                                <th><?php echo _('User can view this message'); ?></th>
                                <th><?php echo _('Delete'); ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            $results = DB::query("SELECT * FROM news");
                            foreach ($results as $row) {
                                echo '<form action="/news/list" method="post"><tr>';
                                echo "<td>" . $row['headline'] . "</td> \n";
                                echo "<td>" . $row['message'] . "</td> \n";
                                ?>
                                <td>
                                    <select name="login_news" size="1" onchange="this.form.submit()">
                                        <option <?php if ($row['login_news'] == '1') {
                                            echo 'selected';
                                        } ?> value="<?php echo $row['id'] . '.1' ?>"><?php echo _('Yes'); ?>
                                        </option>
                                        <option <?php if ($row['login_news'] == '0') {
                                            echo 'selected';
                                        } ?> value="<?php echo $row['id'] . '.0' ?>"><?php echo _('No'); ?>
                                        </option>
                                    </select>
                                </td>
                                <td>
                                    <select name="is_aktiv" size="1" onchange="this.form.submit()">
                                        <option <?php if ($row['is_aktiv'] == '1') {
                                            echo 'selected';
                                        } ?> value="<?php echo $row['id'] . '.1' ?>"><?php echo _('Yes'); ?>
                                        </option>
                                        <option <?php if ($row['is_aktiv'] == '0') {
                                            echo 'selected';
                                        } ?> value="<?php echo $row['id'] . '.0' ?>"><?php echo _('No'); ?>
                                        </option>
                                    </select>
                                </td>
                                <?php
                                echo '<td><button class="btn btn-danger" name="delmes" value="' . $row['id'] . '">'._('Delete').'</button></td>';
                                echo '</tr></form>';
                            }
                            ?>
                            </tbody>
                        </table>

                    </div>
                    <!-- /widget-content -->

                </div>
                <!-- /widget -->

            </div>
            <!-- /span12 -->

        </div>
        <!-- /row -->

    </div>
    <!-- /.container -->

</div> <!-- /#content -->
<?php require __DIR__ . '/../footer.phtml' ?>