<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.37
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
    <div id="content">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="widget widget-table">
                    <div class="widget-header">
                        <h3>
                            <i class="icon-th-list"></i>
                            <?php echo _('User messages'); ?>
                        </h3>
                    </div>
                    <!-- /widget-header -->
                    <div class="widget-content">
                        <table class="table table-striped table-bordered table-highlight" id="example">
                            <thead>
                            <tr>
                                <th><?=  _('Titel'); ?></th>
                                <th><?=  _('Nachricht'); ?></th>
                                <th><?=  _('Login-News?'); ?></th>
                                <th><?=  _('Benutzern die Nachricht zeigen'); ?></th>
                                <th><?=  _('Benutzer soll Nachricht lesen') ?></th>
                                <th><?=  _('Löschen'); ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            $results = DB::query("SELECT * FROM news");
                            foreach ($results as $row) {
                                echo '<form action="/news/list" method="post"><tr>';
                                echo "<td>" . $row['headline'] . "</td> \n";
                                echo "<td>" . $row['message'] . "</td> \n";
                                ?>
                                <td>
                                <?php
                                 if ($row['login_news'] == '0') {?>
                                     <button class="btn btn-danger" value="<?php echo $row['id'] . '.1' ?>" name="login_news" ><?= _('Nein') ?></button>
                                 <?php
                                 }
                                 if ($row['login_news'] == '1') {
                                     ?>
                                <button class="btn btn-success" value="<?php echo $row['id'] . '.0' ?>" name="login_news" ><?= _('Ja') ?></button>
                                     <?php
                                 }
                                    ?>

                                </td>
                                <td>
                                    <?php
                                    if ($row['is_aktiv'] == '0') {?>
                                        <button class="btn btn-danger" value="<?php echo $row['id'] . '.1' ?>" name="is_aktiv" ><?= _('Nein') ?></button>
                                    <?php
                                    }
                                    if ($row['is_aktiv'] == '1') {
                                        ?>
                                        <button class="btn btn-success" value="<?php echo $row['id'] . '.0' ?>" name="is_aktiv" ><?= _('Ja') ?></button>
                                    <?php
                                    }
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    if ($row['have_to_read'] == '0') {?>
                                        <button class="btn btn-danger" value="<?php echo $row['id'] . '.1' ?>" name="have_to_read" ><?= _('Nein') ?></button>
                                    <?php
                                    }
                                    if ($row['have_to_read'] == '1') {
                                        ?>
                                        <button class="btn btn-success" value="<?php echo $row['id'] . '.0' ?>" name="have_to_read" ><?= _('Ja') ?></button>
                                    <?php
                                    }
                                    ?>
                                </td>
                                <?php
                                echo '<td><button class="btn btn-danger" name="delmes" value="' . $row['id'] . '">'._('Löschen').'</button></td>';
                                echo '</tr></form>';
                            }
                            ?>
                            </tbody>
                        </table>

                    </div>
                    <!-- /widget-content -->

                </div>
                <!-- /widget -->

            </div>
            <!-- /span12 -->

        </div>
        <!-- /row -->

    </div>
    <!-- /.container -->

</div> <!-- /#content -->
<?php require __DIR__ . '/../footer.phtml' ?>