<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.18
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 * Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
    <div id="content">

    <div class="container">

        <div class="row">

            <div class="span8">

                <div id="horizontal" class="widget widget-form">

                    <div class="widget-header">
                        <h3>
                            <i class="icon-pencil"></i>
                            <?= _('Add New User'); ?>
                        </h3>
                    </div>
                    <!-- /widget-header -->

                    <div class="widget-content">

                        <form class="form-horizontal" method="post" action="/sap/benutzerverwaltung/list">
                            <fieldset>
                                <div class="control-group">
                                    <label class="control-label" for="input01"><?= _('Consumer ID'); ?></label>

                                    <div class="controls">
                                        <input type="text" class="input-large" name="kundennummer" id="input01">

                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="input01"><?= _('Password'); ?></label>

                                    <div class="controls">
                                        <input type="text" class="input-large" name="password" id="input01">

                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="input01"><?= _('First Name'); ?></label>

                                    <div class="controls">
                                        <input type="text" class="input-large" name="vorname" id="input01">
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="input01"><?= _('Name'); ?></label>

                                    <div class="controls">
                                        <input type="text" class="input-large" name="nachname" id="input01">
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="input01"><?= _('Street'); ?></label>

                                    <div class="controls">
                                        <input type="text" class="input-large" name="street" id="input01">
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="input01"><?= _('Number'); ?></label>

                                    <div class="controls">
                                        <input type="text" class="input-large" name="hausnummer" id="input01">
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="input01"><?= _('ZIP'); ?></label>

                                    <div class="controls">
                                        <input type="text" class="input-large" name="plz" id="input01">
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="input01"><?= _('Town'); ?></label>

                                    <div class="controls">
                                        <input type="text" class="input-large" name="ort" id="input01">
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="input01"><?= _('Phone'); ?></label>

                                    <div class="controls">
                                        <input type="text" class="input-large" name="telefon" id="input01">
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="input01"><?= _('Mobile'); ?></label>

                                    <div class="controls">
                                        <input type="text" class="input-large" name="handy" id="input01">
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="input01"><?= _('Mail'); ?></label>

                                    <div class="controls">
                                        <input type="text" class="input-large" name="mail" id="input01">

                                        <p class="help-block">Wird benötigt bei der Automatischen erstellung des
                                            Passwortes!</p>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label">Benutzerrechte</label>

                                    <div class="controls">
                                        <label class="radio">
                                            <input type="radio" name="usr_grp" id="validateRadio1" value="user">
                                            Benutzer (Starten und Stoppen der Streams, Playlisten bearbeiten, DJ
                                            anlegen, löschen)
                                        </label>
                                        <label class="radio">
                                            <input type="radio" name="usr_grp" id="validateRadio2" value="adm">
                                            Administrator (Streams, Benutzer anlegen und Löschen, Paneleinstellungen
                                            bearbeiten)
                                        </label>
                                    </div>
                                </div>
                                <div class="form-actions">
                                    <button type="submit" class="btn btn-primary btn-large" name="registeruser"><?= _('Add New User'); ?>
                                    </button>
                                </div>
                            </fieldset>
                        </form>

                    </div>
                    <!-- /widget-content -->

                </div>


            </div>
            <!-- /span8 -->


            <div class="span4">

                <div id="formToc" class="widget highlight">

                    <div class="widget-header">
                        <h3><b>-Hinweise- </b>"Benutzer hinzufügen"</h3>
                    </div>
                    <!-- /widget-header -->

                    <div class="widget-content">

                        <p>Kundennummern zur Identifikation von verschiedenen Accounts. Diese kann je nach Einstellungen
                            als Login verwendet werden. </p>

                        <br>

                        <p>Benutzer mit Administrator rechten erhalten vollen Zugriff auf das Panel</p>

                        <br>

                        <p>Automatisch erstellte Passwörter werden den Benutzer per Mail zugeschickt.</p>
                    </div>
                    <!-- /widget-content -->
                </div>
                <!-- /widget -->
            </div>
            <!-- /.span4 -->
        </div>
        <!-- /row -->
    </div>
    <!-- /.container -->
</div> <!-- /#content -->
<?php require __DIR__ . '/../footer.phtml' ?>