<?php
/**
 * Created by David Schomburg (DashTec - Services)
 *      www.dashtec.de
 *
 *  S:P (StreamersPanel)
 *  Support: http://board.streamerspanel.de
 *
 *  v 0.30
 *
 *  Kundennummer:   @KDNUM@
 *  Lizenznummer:   @RECHNR@
 *  Lizenz: http://login.streamerspanel.de/user/terms
 */
?>
<?php require_once __DIR__ . '/../header.phtml' ?>
<div id="content">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="widget widget-table">
                    <div class="widget-header">
                        <h3>
                            <i class="icon-th-list"></i>
                            <?= _('Benutzerliste'); ?>
                        </h3>
                    </div>
                    <!-- /widget-header -->
                    <div class="widget-content">
                        <table class="table table-striped table-bordered table-highlight" id="example">
                            <thead>
                            <tr>
                                <th><?= _('Kundennummer'); ?></th>
                                <th><?= _('Name'); ?></th>
                                <th><?= _('Adresse'); ?></th>
                                <th><?= _('Tel'); ?></th>
                                <th><?= _('Mail'); ?></th>
                                <th><?= _('Benutzergruppe'); ?></th>
                                <th><?= _('Is Aktiv?'); ?></th>
                                <th><?= _('Einstellungen'); ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            foreach ($Users as $row) {
                                echo '<form action="/user/list" method="post"><tr>';
                                echo "<td>" . $row['kundennummer'] . "</td> \n";
                                echo "<td>" . $row['vorname'] . ' ' . $row['nachname'] . "</td> \n";
                                echo "<td>" . $row['street'] . ' ' . $row['hausnummer'] . ', ' . $row['plz'] . ' ' . $row['ort'] . "</td> \n";
                                echo "<td>" . $row['handy'] . "</td> \n";
                                echo "<td>" . $row['mail'] . "</td> \n";
                                if ($row['usr_grp'] == 'adm') {
                                    echo "<td>"._('Admininstrator')."</td> \n";
                                } elseif ($row['usr_grp'] == 'user') {
                                    echo "<td>"._('Benutzer')."</td> \n";
                                } elseif ($row['usr_grp'] == 'dj') {
                                    echo "<td>"._('DJ')."</td> \n";
                                }
                                ?>
                                <td>

                                    <?php if ($row['is_aktiv'] == '1' AND $row['usr_grp'] != 'adm' ) {?>
                                    <button class="btn btn-danger" value="<?php echo $row['id'] . '.0' ?>" name="is_aktiv" ><?= _('Sperren') ?></button>
                                    <?php
                                    }
                                    if ($row['is_aktiv'] == '0') {
                                        ?>
                                    <button class="btn btn-success" value="<?php echo $row['id'] . '.1' ?>" name="is_aktiv" ><?= _('Freischalten') ?></button>
                                    <?php
                                    }

                                    ?>
                                </td>

                                <td>
                                   <button class="btn btn-secondary" value="<?php echo $row['id'] . '.edituser' ?>" name="useredit" ><img src="/image/fuge/pencil.png"></button>
                                   <button class="btn btn-warning" value="<?php echo $row['id'] . '.changePass' ?>" name="useredit" ><img src="/image/fuge/key.png"></button>

                                    <?php if ($row['usr_grp'] != 'adm' ) {?>
                                        <button class="btn btn-danger" value="<?php echo $row['id'] . '.deluser' ?>" name="useredit" ><img src="/image/fuge/cross-circle.png" ></button>

                                    <?php
                                    }
?>
                                </td>
                                <?php
                                echo '</tr></form>';
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                    <!-- /widget-content -->
                </div>
                <!-- /widget -->
            </div>
            <!-- /span12 -->
        </div>
        <!-- /row -->
    </div>
    <!-- /.container -->
</div> <!-- /#content -->
<?php require __DIR__ . '/../footer.phtml' ?>
